### ISSUE TITLE
Does Zoom have to be on for the program to run?

### ISSUE THREAD

**Issue by mastercoder123432** [Owl-dy/autozoom#7]

**Comment by Owl-dy** [comment]
no, i doesnt have to be on. the script opens zoom for you.

**Comment by mastercoder123432** [comment]
Okay. After downloading the script and completing the table, the Zoom app only opens at the meeting's end time and closes immediately without warning. IE I set the meeting end time to 12:01 and start time at 12:20 it will open Zoom and launch meeting at 12:20 and shut off Zoom imediately. Please advise.

**Comment by Owl-dy** [comment]
naturally, the meeting start time should be before the end time..... i think you have it in reversed, you should set your meeting start time at 12:01 and end time at 12:20.

**Comment by Owl-dy** [comment]
close for no further comments
